Resolve documentation pointing to wrong SDK
lowRISC/sonata-system pull request #103
Opened 2024-05-27 08:54 UTC by marnovandermaas

In the documentation we should just recommend that people use cmake to pull in the correct version of the SDK.

2024-05-27 08:55 UTC, marnovandermaas commented
Partially fixes: https://github.com/lowRISC/sonata-system/issues/101

2024-05-27 13:04 UTC, GregAC approved these changes

2024-05-27 13:27 UTC, HU90m requested changes

2024-05-27 13:27 UTC, HU90m commented on doc/guide/building-examples.md
>  The following assume you have run the `source .venv/bin/activate` command in the terminal you are using, and you are
```suggestion
The following assumes you have run the `source .venv/bin/activate` command in the terminal you are using, and you are
```

2024-05-27 13:27 UTC, HU90m commented on doc/guide/building-examples.md
> +
```suggestion
```

2024-05-27 13:28 UTC, HU90m reviewed
Also, there are a few sentences which are split over multiple lines.

2024-05-27 15:09 UTC, nwf commented
I'm not sure I approve of increasingly relying on `cmake` to pull in the RTOS in a section for "advanced users".  Advanced users can probably be told how to ensure that they fetch the suitable version (which, hopefully soon, is just mainline?) and might want to make changes to the RTOS itself, which would be difficult if it's hidden behind `cmake`.  Thoughs?

2024-05-27 15:18 UTC, davidchisnall commented
Why are you wrapping a build system that can target Sonata and comes with a dev container that just works in a load of CMake goo?

For reference, the first CHERIoT build system used CMake, but CMake was not sufficiently flexible to allow defining new kinds of targets and so we abandoned it.

2024-05-27 16:08 UTC, GregAC commented
I would note the software in this repository is intended for system bring-up/test purposes. People wanting to actually develop software for Sonata will use https://github.com/lowRISC/sonata-software or indeed just the upstream CHERIoT RTOS repository: https://github.com/microsoft/cheriot-rtos/.

The main branch of this repository and of the https://github.com/lowRISC/sonata-software are our live development repositories and as such in a state of flux right now. So in particular documentation is still being worked on along with deciding exactly what lives where etc.

We do not intend for cmake to be the primary build system for Sonata software, rather we will use the existing build flows provided by the CHERIoT RTOS upstream. It may remain in use in this repository for the limited use case of building small programs used for verification purposes and only of relevance to hardware engineers working on the RTL but this is not yet decided.

2024-05-28 08:55 UTC, marnovandermaas commented on doc/guide/building-examples.md
> +
Thanks.

2024-05-28 08:55 UTC, marnovandermaas commented on doc/guide/building-examples.md
>  The following assume you have run the `source .venv/bin/activate` command in the terminal you are using, and you are
Thanks

2024-05-28 09:00 UTC, merged