DRAFT: Migrate SPI CS control into the controllers
lowRISC/sonata-system pull request #198
Opened 2024-09-19 19:11 UTC by alees24

Modify the SPI controller to incorporate a parameterised number of CS (Chip Select) lines to the attached peripherals.

Since the SPI controllers share a single auto-generated register implementation the intention is to set the parameter to be large enough that all SPI controllers are accommodated, and the surplus CS lines in some controls will simply be unused and unconnected.

The number of controllers and the mapping of peripheral CS lines to controllers is expected to change, but for now we allow up to 4 peripherals per controllers and track all of the CS lines out of `sonata_system` into the top level. The maximum number of CS lines required per controller is presently 3, for one of the SPI buses on the Raspberry Pi header.

Compatibility with the existing software tree is maintained by combining the GPIO-driven CS lines with those from the controller itself. In time the GPIO lines shall be dropped.

**This is a draft PR for now,** pending some feedback on the way the CS lines have been implemented and the chosen parameters. Proof-of-concept has been demonstrated on FPGA by modifying `sw/cheri/checks/spi_test` to operate either using the GPIO or using the SPI CS register, and the same results are observed in each case.

2024-10-02 09:00 UTC, HU90m reviewed
The chip select (CS) register layout looks sensible to me.

If we want auto chip select in the future, we could add a second register which like the CS register has a bit for each CS line. When this bit is set high, the auto chip select is enabled and the CS register becomes read-only.

2024-10-04 10:49 UTC, GregAC approved these changes
LGTM modulo one nit, thanks @alees24 

We should write some test to check the interrupts actually work, but no required for this PR. Maybe time to spin up an initial block level DV environment for this...

2024-10-04 10:49 UTC, GregAC commented on dv/verilator/top_verilator.sv
> +  logic [SPI_CS_NUM-1:0] spi_cs[SPI_NUM];
nit: align `spi_rx`/`spi_tx`/`spi_clk` with `spi_cs`

2024-10-04 10:58 UTC, GregAC commented on rtl/ip/spi/rtl/spi.sv
> +  parameter int unsigned RxFifoDepth = 16,
FYI at the last sunburst meeting we decided we should go for a depth of 8 for FIFOs across the board. The thinking being right now tiny FIFOs are fine and it's easier to increase the depth rather than decrease.

2024-10-04 12:35 UTC, alees24 commented
> LGTM modulo one nit, thanks @alees24
> 
> We should write some test to check the interrupts actually work, but no required for this PR. Maybe time to spin up an initial block level DV environment for this...

Writing an interrupt test is on my ToDo list.

2024-10-04 16:43 UTC, marnovandermaas requested changes
Adding this request for change because CI lint is failing.

2024-10-04 17:34 UTC, marnovandermaas reviewed
Some comments from just reading the code.

2024-10-04 17:34 UTC, marnovandermaas commented on rtl/ip/spi/rtl/spi.sv
> +  // core is Idle.
What is stopping this update from happening when the block isn't idle?

2024-10-04 17:34 UTC, marnovandermaas commented on rtl/ip/spi/rtl/spi_reg_top.sv
> +// Copyright lowRISC contributors (OpenTitan project).
I know this is autogenerated but not sure we want to add this.

2024-10-04 17:34 UTC, marnovandermaas commented on rtl/system/sonata_pkg.sv
> +  localparam int unsigned SPI_CS_NUM = 4;
This file is auto generated did you add it in the template?

2024-10-04 17:34 UTC, marnovandermaas commented on rtl/system/sonata_system.sv
> +  import sonata_pkg::*;
Nice! Didn't know you could do this :)

2024-10-07 10:23 UTC, alees24 commented on rtl/ip/spi/rtl/spi.sv
> +  // core is Idle.
We are relying upon software to modify the CS lines only when the block is idle, just as when it was using the GPIO lines; it can ascertain the idle/busy state of the SPI core from the `status` register.

2024-10-07 11:30 UTC, alees24 commented on rtl/system/sonata_pkg.sv
> +  localparam int unsigned SPI_CS_NUM = 4;
Thanks for the prompt; I hadn't registered that it was generated.

2024-10-07 15:59 UTC, GregAC commented on rtl/ip/spi/rtl/spi.sv
> +  // core is Idle.
I happy to leave this behaviour as is given it's exactly as it was before (i.e. SW needs to know when it's safe to alter CS line states).

We could always add this as a new feature. Some argument as it's software visible we should do this pre v1.0 but feels like an innocuous enough change to me (shades of https://xkcd.com/1172/ for anyone who complains being able to alter CS whilst the block is active is an essential feature ;) ).

2024-10-09 11:35 UTC, GregAC commented
@alees24 would be good to get this merged. Looks like the current CI failure is just down to https://github.com/lowRISC/cheriot-rtos/pull/4 needing to be merged so we can update the CHERIoT RTOS commit used by cmake for the sonata-system software build.

2024-10-09 22:04 UTC, alees24 commented
Thanks to @hcallahan-lowrisc and @HU90m for help sorting out the cross-repo fun.

2024-10-10 09:29 UTC, marnovandermaas approved these changes
Thanks lets merge this.

2024-10-10 09:29 UTC, merged