Connect MicroSD card slot to an SPI controller
lowRISC/sonata-system pull request #239
Opened 2024-10-14 16:10 UTC by elliotb-lowrisc

Wire up the on-board MicroSD card slot to an existing SPI controller via pinmux.
CS line is connected at top-level.
Card detection is connected to fixed GPI.

As-yet untested.

2024-10-14 16:30 UTC, elliotb-lowrisc commented
Remove attempt at using `spidpi` for MicroSD

2024-10-17 13:48 UTC, GregAC commented
@HU90m @marnovandermaas @AlexJones0 need to consider the SD card SPI connection as well when deciding on the final pinmux setup

2024-10-17 18:09 UTC, alees24 requested changes
This looks basically sound but a few connections could probably be tidied, please:
 - `top_verilator.microsd_dat0` is undriven, I think.
 - the pin connections `micro_sd_dat1` and `microsd_dat2` in pins_sonata.xdc should probably be commented-out, with an explanation, to match the commented-out port connections in top_sonata.sv; this mismatch presently leads to build warnings.

2024-10-18 09:18 UTC, elliotb-lowrisc commented
Thanks for the review @alees24. I commented out the pins_sonata.xdc and added a quick explanation. I couldn't find the undriven `top_verilator.microsd_dat0` signal you mentioned, but I'm also not familiar with the Sonata Verilator sim.

2024-10-19 00:54 UTC, alees24 approved these changes
Thanks for adding the comments about the extra pins that we don't use in SPI mode. Having now got PoC microSD card reading working I've convinced myself that the external pull ups (discussed verbally) are sufficient and that we don't need to modify the SPI core to use the microSD card (we may still need to enable transmit and receive simultaneously whilst awaiting the first response byte).

Regards the undriven input to the pinmux, it's not causing simulation problems and it's likely irrelevant in the face of other pinmux changes.

I'll probably knock up a DPI model of a basic SD card in time anyway. Thanks.

2024-10-22 12:06 UTC, elliotb-lowrisc commented
Rebased to include recent pinmux changes

2024-10-23 18:24 UTC, alees24 commented
Unfortunately there are three now-disconnected signals following the rebase:
```
diff --git a/rtl/fpga/top_sonata.sv b/rtl/fpga/top_sonata.sv
index ebd28c7..2ead6e0 100644
--- a/rtl/fpga/top_sonata.sv
+++ b/rtl/fpga/top_sonata.sv
@@ -440,18 +440,21 @@ module top_sonata
   );
 
   // Input Pins
-  assign in_from_pins[IN_PIN_MB8        ] = mb8;
-  assign in_from_pins[IN_PIN_MB3        ] = mb3;
-  assign in_from_pins[IN_PIN_ETHMAC_CIPO] = ethmac_cipo;
-  assign in_from_pins[IN_PIN_APPSPI_D1  ] = appspi_d1;
-  assign in_from_pins[IN_PIN_RS232_RX   ] = rs232_rx;
-  assign in_from_pins[IN_PIN_SER1_RX    ] = ser1_rx;
-  assign in_from_pins[IN_PIN_SER0_RX    ] = ser0_rx;
+  assign in_from_pins[IN_PIN_MICROSD_DAT0] = microsd_dat0;
+  assign in_from_pins[IN_PIN_MB8         ] = mb8;
+  assign in_from_pins[IN_PIN_MB3         ] = mb3;
+  assign in_from_pins[IN_PIN_ETHMAC_CIPO ] = ethmac_cipo;
+  assign in_from_pins[IN_PIN_APPSPI_D1   ] = appspi_d1;
+  assign in_from_pins[IN_PIN_RS232_RX    ] = rs232_rx;
+  assign in_from_pins[IN_PIN_SER1_RX     ] = ser1_rx;
+  assign in_from_pins[IN_PIN_SER0_RX     ] = ser0_rx;
 
   // Output Pins
   // pull output pins low when their output isn't enabled.
   assign output_pins = out_to_pins_en & out_to_pins;
 
+  assign microsd_cmd = output_pins[OUT_PIN_MICROSD_CMD];
+  assign microsd_clk = output_pins[OUT_PIN_MICROSD_CLK];
   assign mb7         = output_pins[OUT_PIN_MB7        ];
   assign mb4         = output_pins[OUT_PIN_MB4        ];
   assign mb2         = output_pins[OUT_PIN_MB2        ];
```

With the above changes in place it's working, thanks.

2024-10-24 09:33 UTC, elliotb-lowrisc commented
Thanks, have included patch

2024-10-24 10:24 UTC, alees24 commented
Thanks.

2024-10-24 10:24 UTC, merged