gpio: Split the gpio into separate blocks
lowRISC/sonata-system pull request #290
Opened 2024-10-29 13:41 UTC by HU90m

The last of the mammoths

2024-10-29 14:53 UTC, marnovandermaas reviewed
Initial comments as I have gone through.

2024-10-29 14:53 UTC, marnovandermaas commented on data/top_config.toml
> +xbar = { pipeline = "true", req_fifo_pass = "false", rsp_fifo_pass = "false" }
These should be two instances of gpio_pmod

2024-10-29 14:53 UTC, marnovandermaas commented on rtl/ip/gpio/rtl/gpio.sv
> +    .RegAddr
I needed to add this to pass on Vivado.

2024-10-29 14:53 UTC, marnovandermaas commented on rtl/system/sonata_system.sv
> +    .gpio_board_gpi_o(),
What about the from pins here?

2024-10-29 15:02 UTC, HU90m commented on rtl/system/sonata_system.sv
> +    .gpio_board_gpi_o(),
Ah thanks! I didn't add these back after the first commit

2024-10-29 16:17 UTC, marnovandermaas commented on rtl/system/sonata_system.sv
> +    .gpio_board_gpi_o(),
Added this in and also corrected the enable later on.

2024-10-29 16:22 UTC, marnovandermaas commented on rtl/ip/gpio/rtl/gpio.sv
> +    .RegAddr
Unfortunately still broken with my latest commit, but will fix this shortly.

2024-10-29 16:49 UTC, marnovandermaas commented on rtl/ip/gpio/rtl/gpio.sv
> +    .RegAddr
Should now be fixed with latest commit.

2024-10-29 20:55 UTC, AlexJones0 commented on rtl/system/sonata_system.sv
> +    .gpio_board_gpi_o(),
Has this been added back in? It still seems to be disconnected for me. If it is and I'm somehow missing something please re-resolve the conversation.

2024-10-29 21:59 UTC, alees24 requested changes

2024-10-29 21:59 UTC, alees24 commented on rtl/ip/gpio/rtl/gpio.sv
Suggestion: drop RegAddrWidth localparam, and rename the 'RegAddr' parameter to the gpio module to be 'RegAddrWidth' with a default value of 6.
This should resolve the current address decoding issue where too many address bits are propagated into the `gpio_core` module. Currently only the the first GPIO block will be accessible from software.

2024-10-29 21:59 UTC, alees24 commented on rtl/ip/gpio/rtl/gpio.sv
> +  parameter int unsigned RegAddr      = 12
As per the other comment, please change to `RegAddrWidth = 6`

2024-10-29 21:59 UTC, alees24 commented on rtl/system/sonata_system.sv
> +    .tl_gpio_pmod_i   (tl_gpio_pmod_d2h),
Experimentally I tried a build from this PR and it fails to meet timing by 1.2ns on a few signals which is the first time I've had a timing failure for a while.

I'm _not_ saying that this PR specifically is responsible (I haven't done other builds from main for a day or two), but it's something that may need attention.

Separating GPIO instances onto separate TL-UL _and then squishing them down to be so close together_ does move more of the address decoding up to the host ports of the Ibex and risk longer paths in the SRAM/HyperRAM connectivity, whereas previously this additional decoding/checking of the lower address bits was safely on the other side of the pipeline stage/TL-UL FIFOs.

2024-10-29 23:06 UTC, alees24 commented on rtl/system/sonata_system.sv
> +    .tl_gpio_pmod_i   (tl_gpio_pmod_d2h),
It's perhaps also worth noting that whether the GPIO blocks are implemented as a single TL-UL device (as before with the gpio_array) or multiple devices is not really a software-facing/visible so could be deferred if this causes problems, provided of course that the address map has stabilised.

2024-10-29 23:31 UTC, alees24 commented
Using the 'CS' lines of the SPI controller to drive the supplementary LCD module inputs is expedient but seems a little unclean. It may also not play well with any future attempt to make the SPI controller drive them automatically.

Nonetheless, there are some missing LCD connections:
```
diff --git a/rtl/fpga/top_sonata.sv b/rtl/fpga/top_sonata.sv
index b54ba9f..d583b06 100644
--- a/rtl/fpga/top_sonata.sv
+++ b/rtl/fpga/top_sonata.sv
@@ -399,27 +399,30 @@ module top_sonata
   // pull output pins low when their output isn't enabled.
   assign output_pins = out_to_pins_en & out_to_pins;
 
-  assign usrLed       = output_pins[OUT_PIN_USRLED_7:OUT_PIN_USRLED_0];
-  assign microsd_dat3 = output_pins[OUT_PIN_MICROSD_DAT3];
-  assign microsd_cmd  = output_pins[OUT_PIN_MICROSD_CMD ];
-  assign microsd_clk  = output_pins[OUT_PIN_MICROSD_CLK ];
-  assign mb10         = output_pins[OUT_PIN_MB10        ];
-  assign mb7          = output_pins[OUT_PIN_MB7         ];
-  assign mb4          = output_pins[OUT_PIN_MB4         ];
-  assign mb2          = output_pins[OUT_PIN_MB2         ];
-  assign mb1          = output_pins[OUT_PIN_MB1         ];
-  assign ethmac_cs    = output_pins[OUT_PIN_ETHMAC_CS   ];
-  assign ethmac_sclk  = output_pins[OUT_PIN_ETHMAC_SCLK ];
-  assign ethmac_copi  = output_pins[OUT_PIN_ETHMAC_COPI ];
-  assign lcd_cs       = output_pins[OUT_PIN_LCD_CS      ];
-  assign lcd_clk      = output_pins[OUT_PIN_LCD_CLK     ];
-  assign lcd_copi     = output_pins[OUT_PIN_LCD_COPI    ];
-  assign appspi_cs    = output_pins[OUT_PIN_APPSPI_CS   ];
-  assign appspi_clk   = output_pins[OUT_PIN_APPSPI_CLK  ];
-  assign appspi_d0    = output_pins[OUT_PIN_APPSPI_D0   ];
-  assign rs232_tx     = output_pins[OUT_PIN_RS232_TX    ];
-  assign ser1_tx      = output_pins[OUT_PIN_SER1_TX     ];
-  assign ser0_tx      = output_pins[OUT_PIN_SER0_TX     ];
+  assign usrLed        = output_pins[OUT_PIN_USRLED_7:OUT_PIN_USRLED_0];
+  assign microsd_dat3  = output_pins[OUT_PIN_MICROSD_DAT3 ];
+  assign microsd_cmd   = output_pins[OUT_PIN_MICROSD_CMD  ];
+  assign microsd_clk   = output_pins[OUT_PIN_MICROSD_CLK  ];
+  assign mb10          = output_pins[OUT_PIN_MB10         ];
+  assign mb7           = output_pins[OUT_PIN_MB7          ];
+  assign mb4           = output_pins[OUT_PIN_MB4          ];
+  assign mb2           = output_pins[OUT_PIN_MB2          ];
+  assign mb1           = output_pins[OUT_PIN_MB1          ];
+  assign ethmac_cs     = output_pins[OUT_PIN_ETHMAC_CS    ];
+  assign ethmac_sclk   = output_pins[OUT_PIN_ETHMAC_SCLK  ];
+  assign ethmac_copi   = output_pins[OUT_PIN_ETHMAC_COPI  ];
+  assign lcd_backlight = output_pins[OUT_PIN_LCD_BACKLIGHT];
+  assign lcd_dc        = output_pins[OUT_PIN_LCD_DC       ];
+  assign lcd_rst       = output_pins[OUT_PIN_LCD_RST      ];
+  assign lcd_cs        = output_pins[OUT_PIN_LCD_CS       ];
+  assign lcd_clk       = output_pins[OUT_PIN_LCD_CLK      ];
+  assign lcd_copi      = output_pins[OUT_PIN_LCD_COPI     ];
+  assign appspi_cs     = output_pins[OUT_PIN_APPSPI_CS    ];
+  assign appspi_clk    = output_pins[OUT_PIN_APPSPI_CLK   ];
+  assign appspi_d0     = output_pins[OUT_PIN_APPSPI_D0    ];
+  assign rs232_tx      = output_pins[OUT_PIN_RS232_TX     ];
+  assign ser1_tx       = output_pins[OUT_PIN_SER1_TX      ];
+  assign ser0_tx       = output_pins[OUT_PIN_SER0_TX      ];
 
   // Inout Pins
   padring #(
```

2024-10-30 13:31 UTC, marnovandermaas commented on rtl/system/sonata_system.sv
> +    .tl_gpio_pmod_i   (tl_gpio_pmod_d2h),
We've removed this now and gone back to having this logic inside gpio array.

2024-10-30 13:31 UTC, marnovandermaas commented on rtl/ip/gpio/rtl/gpio.sv
> +  parameter int unsigned RegAddr      = 12
Thanks this change has been made.

2024-10-30 14:58 UTC, AlexJones0 reviewed
Can confirm that as of my latest push, the manual pinmux "all blocks" check procedure is passing on an FPGA build.

As a general comment: the GPIO changes in this PR only make sure that CI (`test_runner`) and the manual "all blocks" pinmux check procedure continue working. Other demos might break, but those should probably be addressed in follow-up PRs, as many have already been broken and I think we should avoid stacking too much onto this 1 PR.

2024-10-30 15:01 UTC, alees24 approved these changes
Thanks for all the work and the tidy ups.

2024-10-30 16:01 UTC, marnovandermaas approved these changes
Cheri Sanity now also passes so I'm going to approve this.

2024-10-30 16:17 UTC, merged